//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_pt4_S4A_eq1Entities : DbContext
    {
        public BD_pt4_S4A_eq1Entities()
            : base("name=BD_pt4_S4A_eq1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<animal> animal { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<facture_produit> facture_produit { get; set; }
        public virtual DbSet<maladie> maladie { get; set; }
        public virtual DbSet<maladie_liee> maladie_liee { get; set; }
        public virtual DbSet<ordonnance> ordonnance { get; set; }
        public virtual DbSet<patient> patient { get; set; }
        public virtual DbSet<produit_vendu> produit_vendu { get; set; }
        public virtual DbSet<salarie> salarie { get; set; }
        public virtual DbSet<traitement> traitement { get; set; }
        public virtual DbSet<produit> produit { get; set; }
        public virtual DbSet<rendez_vous> rendez_vous { get; set; }
    }
}
