//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT4
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produit()
        {
            this.traitement = new HashSet<traitement>();
        }
    
        public int idProduit { get; set; }
        public string nomProduit { get; set; }
        public string description { get; set; }
        public int quantiteStock { get; set; }
        public decimal prixAchat { get; set; }
        public decimal prixVenteClient { get; set; }
        public Nullable<int> idOrdonnance { get; set; }
        public byte[] imageProduit { get; set; }
    
        public virtual ordonnance ordonnance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<traitement> traitement { get; set; }
    }
}
