//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT4
{
    using System;
    using System.Collections.Generic;
    
    public partial class traitement
    {
        public int idTraitement { get; set; }
        public int idMaladie { get; set; }
        public int idProduit_ { get; set; }
    
        public virtual maladie maladie { get; set; }
        public virtual produit produit { get; set; }
    }
}
